export const LEARNED_SO_FAR = 12;
export const alphabets = [{
  letter: 'alif',
    image: 'alif.jpg',
  }, {
    letter: 'ba',
    image: 'ba.jpg',
  }, {
  letter: 'tha',
    image: 'tha.jpg',
  }, {
    letter: 'thsa',
    image: 'thsa.jpg',
  }, {
    letter: 'jeem',
    image: 'jeem.jpg',
  }, {
  letter: 'ha',
    image: 'ha.jpg',
  }, {
    letter: 'kha',
    image: 'kha.jpg',
  }, {
    letter: 'dal',
    image: 'dal.jpg',
  }, {
  letter: 'dhal',
    image: 'dhal.jpg',
  }, {
    letter: 'ra',
    image: 'ra.jpg',
  }, {
    letter: 'za',
    image: 'za.jpg',
  }, {
  letter: 'seen',
    image: 'seen.jpg',
  }, {
    letter: 'sheen',
    image: 'sheen.jpg',
  }, {
    letter: 'swad',
    image: 'swad.jpg',
  }, {
  letter: 'dhwad',
    image: 'dhwad.jpg',
  }, {
    letter: 'twa',
    image: 'twa.jpg',
  }, {
    letter: 'dhwa',
    image: 'dhwa.jpg',
  }, {
  letter: 'aain',
    image: 'aain.jpg',
  }, {
    letter: 'gaain',
    image: 'gaain.jpg',
  }, {
    letter: 'fa',
    image: 'fa.jpg',
  }, {
  letter: 'qaf',
    image: 'qaf.jpg',
  }, {
    letter: 'kaaf',
    image: 'kaaf.jpg',
  }, {
    letter: 'laam',
    image: 'laam.jpg',
  }, {
  letter: 'meem',
    image: 'meem.jpg',
  }, {
    letter: 'noon',
    image: 'noon.jpg',
  }, {
    letter: 'haaa',
    image: 'haaa.jpg',
  }, {
    letter: 'wa',
    image: 'wa.jpg',
  }, {
    letter: 'ya',
    image: 'ya.jpg',
  }];